# Generated by Django 4.2.2 on 2023-06-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_imagepath_product_photo_0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo_0',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
