# Generated by Django 4.2.2 on 2023-07-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_contactmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactModel',
            new_name='ContactRequest',
        ),
    ]
